site_name: pg_migrate
site_url: https://olirice.github.io/pg_migrate
site_description: A PostgreSQL extension for migrations and DDL tracking

theme:
    name: 'material'

repo_name: olirice/pg_migrate
repo_url: https://github.com/olirice/pg_migrate

nav:
    - Introduction: 'index.md'
    - Quickstart: 'quickstart.md'
    - API Reference: 'api.md'

markdown_extensions:
  - codehilite
  - admonition
