name: pre-commit hooks

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: checkout
      uses: actions/checkout@v2

    - name: set up python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8

    - name: install
      run: |
        python -m pip install --upgrade pip
        pip install pre-commit

    - name: run
      run: |
        pre-commit run --all-files
