name: tests

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: harmon758/postgresql-action@v1
      with:
        postgresql version: '12'

    - uses: actions/checkout@v1

    - name: install postgres
      run: |
        # Create the file repository configuration:
        sh -c 'echo "deb http://apt.postgresql.org/pub/repos/apt $(lsb_release -cs)-pgdg main" > /etc/apt/sources.list.d/pgdg.list'

        # Import the repository signing key:
        wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | sudo apt-key add -

        # Update the package lists:
        apt-get update

        # Install the latest version of PostgreSQL.
        # If you want a specific version, use 'postgresql-12' or similar instead of 'postgresql':
        apt-get -y install postgresql

    - name: test
      run: |
        make install && make installcheck
