name: tests

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: harmon758/postgresql-action@v1
      with:
        postgresql version: '12'

    - uses: actions/checkout@v1

    - name: test
      run: |
        make install && make installcheck
